import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import './globals.css'
import { getServerSession } from 'next-auth'
import SessionProvider from '@/components/SessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'My NextJS App',
	description: 'Generated by Joshua Wilde Hawk using create next app'
}

export default async function RootLayout({ children }) {
	const session = await getServerSession()

	return (
		<html lang="en" className={inter.className}>
			<body>
				<SessionProvider session={session}>
					<main className="px-4 mx-auto my-8 max-w-7xl">
						<Navbar />
						{children}
					</main>
				</SessionProvider>
			</body>
		</html>
	)
}
