import { Inter, Roboto_Mono } from 'next/font/google'
import Navbar from '@/components/Navbar'
import './globals.css'

const inter = Inter({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-inter',
})

const robotoMono = Roboto_Mono({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-roboto-mono',
})

export const metadata = {
	title: 'My NextJS App',
	description: 'Generated by Joshua Wilde Hawk using create next app',
}

export default function RootLayout({ children }) {
	return (
		<html
			lang='en'
			className={`${inter.variable} ${robotoMono.variable}`}>
			<body>
				<Navbar />
				<main>{children}</main>
			</body>
		</html>
	)
}
