import { Roboto_Flex, Roboto_Slab, Roboto_Mono } from 'next/font/google'
import Navbar from '@/components/Navbar'
import '@/styles/globals.css'
import { getServerSession } from 'next-auth'
import SessionProvider from '@/components/SessionProvider'

const robotoFlex = Roboto_Flex({
	subsets: ['latin'],
	variable: '--font-roboto-flex'
})
const robotoSlab = Roboto_Slab({
	subsets: ['latin'],
	variable: '--font-roboto-slab'
})
const robotoMono = Roboto_Mono({
	subsets: ['latin'],
	variable: '--font-roboto-mono'
})

export const metadata = {
	title: `Hawk's Nest Social`,
	description: 'Generated by Joshua Wilde Hawk using create next app'
}

export default async function RootLayout({ children }) {
	const session = await getServerSession()

	return (
		<html lang="en">
			<body className={`${robotoFlex.variable} ${robotoSlab.variable} ${robotoMono.variable}`}>
				<SessionProvider session={session}>
					<main className="px-4 mx-auto my-8 max-w-7xl">
						<Navbar />
						{children}
					</main>
				</SessionProvider>
			</body>
		</html>
	)
}
